### ISSUE TITLE
Bug With Cyberware (Server Exception)

### ISSUE THREAD

**Issue by RainbowDash956** [Y0ungSandwich/Mech-and-Magic#128]
This bug just started happening in my server. Whenever someone logs in it displays this error (image linked below.) Happened after I installed the Metabolic Generator upgrade from Cyberwares. After that it was a seemingly random amount of time time until this just happened. Didn't know if this is the right place for this but plz fix. 

[Image of server error](http://imgur.com/a/D4Ouk)

**Comment by RainbowDash956** [comment]
Still does it even after update from 1.0.4 to 1.0.5.

**Comment by Cuppycake** [comment]
Not really an issue.  If it's not causing lag,  user issues,  or crashes it should be fine to ignore.

**Comment by RainbowDash956** [comment]
Its causing me and a friend to crash to menu whenever we attempt to join.

**Comment by Cuppycake** [comment]
Is it just you two on the server?

**Comment by RainbowDash956** [comment]
Us and one other. The other one can join fine and he didnt install any cyberware upgrades.

**Comment by Cuppycake** [comment]
Can either delete you player datas or load the server once with no cyberware mod and than put it back.

**Comment by RainbowDash956** [comment]
I deleted the NBT associated with cyberware. Fixes it. Gonna try to see if I can replicate the issue or if its just a one-time thing.

**Comment by RainbowDash956** [comment]
Just happened again.

[Screenshot of console](http://imgur.com/a/BmZEI)

**Comment by Cuppycake** [comment]
Please stop screenshoting the console.  Leave a log of anything.  I can't send a screenshot to a mod author and expect help.

**Comment by RainbowDash956** [comment]
Here's the server logs folder. 

[Link to logs.](https://www.dropbox.com/s/tbi4tnx0k9n420v/logs.zip?dl=0)
