### ISSUE TITLE
Yabba Hammer/Paint Roller Crashing Game

### ISSUE THREAD

**Issue by G4ivl3** [Y0ungSandwich/Mech-and-Magic#135]
http://pastebin.com/rtj9wDdK

Once you crash, the pack will automaticlly start to load back up. Once I had fatal errors when trying to connect. The second time it went thru. To fix the fatal error to shut down ATLauncher, then just reload as normal.

**Comment by Y0ungSandwich** [comment]
Fixed as of 1.0.13
