### ISSUE TITLE
./help 8

### ISSUE THREAD

**Issue by Redeye213n** [Y0ungSandwich/Mech-and-Magic#143]
anytime i do the command above a error i get then after a little time goes by i crash

http://paste.atlauncher.com/view/45cd252e

**Comment by Y0ungSandwich** [comment]
Please provide a crash report.

**Comment by Redeye213n** [comment]
thats the thing there is no crash report https://www.youtube.com/watch?v=S_6N0CNDcqY 

when i die i glitch out and the only way to fix it is to relog

**Comment by Redeye213n** [comment]
its a crash that does not produce a crash report the only thing i could get about what happen is from the above linkkl

**Comment by Y0ungSandwich** [comment]
A crash report will surely generate if the game crashes to desktop. Unless you can reproduce and get me a report I'm going to close this as we can not reproduce it and no one else has brought this to our attention.

**Comment by Y0ungSandwich** [comment]
Closing due to lack of continued information. Can not reproduce.
