### ISSUE TITLE
[1.1.1HF] Immersive Engineering manual displays missing textures

### ISSUE THREAD

**Issue by Entih** [Y0ungSandwich/Mech-and-Magic#146]
Due to some change in the M&M 1.1.1 or 1.1.1HF updates, the multiblock structure instructions in Immersive Engineering's manual are broken, displaying missing textures on blocks that, in inventory and in game, are not missing textures.

I have confirmed that the issue is not with Immersive Engineering's update, as downgrading the .jar to the version in 1.1.0 did not fix the issue.  Removing optifine and performance enhancing mods also failed to alleviate the issue, as did reinstalling the pack from scratch, leaving the conclusion that a change in 1.1.1 or the hotfix caused it.

Issue is also unlikely with Immersive Engineering on its own, as prior builds have not had issue, and issue was not experienced outside the Mech and Magic 1.1.1 build.

Included is a screenshot of the issue, on the Immersive Engineering "Excavator" instruction page.

![2017-02-21_16 58 06](https://cloud.githubusercontent.com/assets/25938940/23187300/47950184-f858-11e6-92cb-3786b0d90bdd.png)

**Comment by Y0ungSandwich** [comment]
100% positive optifine isn't in the instance?  There really is nothing else that can mess with a texture besides that and foamfix.  Waiting to confirm on any other clients now.

**Comment by Entih** [comment]
Absolutely certain.  In my fidgeting I completely removed optifine and anything else that boasts performance or visual improving from the instance.  The only change is that the missing texture changed to a pink and black checkerboard rather than matte pink.

**Comment by Y0ungSandwich** [comment]
We have noticed this on every client.  Not something we checked for so are you able to confirm if the textures were there in the previous version(s) of the pack?

**Comment by Entih** [comment]
Having played this save since 1.1.0, I can confirm the manual's textures worked prior to the 1.1.1 update, as the error took me by surprise when I updated the pack.

**Comment by Eforen** [comment]
Is this happening on a Mac or PC? 

If mac what kinda and what version of Mac OS X

If PC what version is your graphics driver and what graphics card do you have?

**Comment by Entih** [comment]
I an running on PC, Windows 10.  My video card is a GeForce 970 on the latest driver, 378.66.  No change in driver prior to or until the onset of this problem.  Only change is the Mech and Magic 1.1.1 update and all it entails.

I intentionally went through mods changed or added in the update and had difficulty finding anything that could be the issue, haven't found a way to rectify yet.  I assume, thus, its a mod that may not be immediately expected having some kind of cross-interference.

**Comment by Y0ungSandwich** [comment]
Well IE was updated with the update.  Unless you pulled this new version of IE into an older version of M&M and confirmed its still happening I'm gonna say it's just the version put out by the mod author.  Nothing else in the pack past the enhancers will change another mods textures like that.

**Comment by Entih** [comment]
I did exactly that actually.  I pulled the updated IE into the 1.1.0 pack.  I also attempted to downgrade IE to the version from 1.1.0.  Neither fixed IE in the 1.1.1 version.

**Comment by Entih** [comment]
As you can see, a clean instance on 1.1.0 with the new version of IE ported in to replace the old, the textures inside the manual's multiblock display are unmolested.

![2017-02-22_12 10 07](https://cloud.githubusercontent.com/assets/25938940/23223086/0b3f79e4-f8f8-11e6-960d-74811e896a52.png)

**Comment by Entih** [comment]
Disabling and re-enabling updated mods in batches has allowed me to cut the culprits down to one of three mods.  The culprit is either:
Chisel
Chisels & Bits
Drawers & Bits

Chisel is suspect number one and I will edit this comment to confirm once I test on Chisel specifically.

**Comment by Entih** [comment]
An update to the Chisel mod was released which may fix the issue.  0.0.8.12

**Comment by Y0ungSandwich** [comment]
Alrighty. Unless it's a game breaking issue it won't be updated for about a week.

**Comment by Entih** [comment]
Quite alright, just glad to help solve a bug.  I can now confirm the updated version of Chisel also fixes the issue.  Cheers.
