### ISSUE TITLE
crash that turned chests to beds

### ISSUE THREAD

**Issue by parkervcp** [Y0ungSandwich/Mech-and-Magic#148]
Here is the crash-log and a screen shot of what I was trying to do.

[crash-2017-03-01_08.16.57-server.txt](https://github.com/Y0ungSandwich/Mech-and-Magic/files/813979/crash-2017-03-01_08.16.57-server.txt)

![mandm crash image](https://cloud.githubusercontent.com/assets/1207679/23510179/87061f36-ff26-11e6-8901-ad84112a6f18.png)

**Comment by Y0ungSandwich** [comment]
Well the crash is what caused the world to corrupt on close changing items to other items.  No fixing that besides manually or pulling from a backup.  That pic doesn't tell me anything you were doing though.  Could be a dozen things.

**Comment by parkervcp** [comment]
I had replaced all the parts to what I was doing.

The quark chest with EnderIO item conduits to feed a Tech Reborn Thermal Generator. There is also some AE2 stuff in the background.
