### ISSUE TITLE
Mech&Magic crashes right before it is about to finish launching.

### ISSUE THREAD

**Issue by Gamerthekid** [Y0ungSandwich/Mech-and-Magic#150]
I start by pressing play on Mech&Magic in the instance tab and it starts working all the way up until it hits the very end ( you know the 7/7 loading bar on forge) then it crashes.

here are my logs: http://paste.atlauncher.com/view/fbdbacc4

**Comment by Y0ungSandwich** [comment]
Allocate more ram.  Closer to 4gb.
