### ISSUE TITLE
Immersive Engineering Coke Ovens

### ISSUE THREAD

**Issue by Mattokah1** [Y0ungSandwich/Mech-and-Magic#155]
When completing the multiblock structure, a second entity of the oven appears next to the original. 
![2017-03-28_13 17 20](https://cloud.githubusercontent.com/assets/13389685/24420724/6043ff88-13b9-11e7-9837-a3b5b40d91e5.png)

**Comment by Y0ungSandwich** [comment]
Can't use it or access it?  Vanish on log?

**Comment by Mattokah1** [comment]
They are not accessible, you can walk through them, and they do not disappear on log. Triff says rebuilding can fix it but it doesn't seem to work here

**Comment by Y0ungSandwich** [comment]
Appears to be an issue with sponge surprise.

**Comment by SOCKPUPP3TS** [comment]
Another thing with the coke ovens is when you turn it into the multi block and break the center block it multiplies, so you get two back instead of one.
