### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by lordalucard123** [Y0ungSandwich/Mech-and-Magic#157]
after the latest update magic&tech no longer opens it just crashes (goes back to the launcher) and i already know this ran on my computer because i played it quite often but now i can't even play it anymore 
any help?

**Comment by Y0ungSandwich** [comment]
Provide a crash report via pastebin

**Comment by lordalucard123** [comment]
How? 
Idk if you understood what i meant but every time i launch it it loads up then goes straight back to the launcher

**Comment by Y0ungSandwich** [comment]
Provide a crash report.

**Comment by lordalucard123** [comment]
Again how

**Comment by Y0ungSandwich** [comment]
Obviously from the crash report folder of your mech & magic instance.

**Comment by lordalucard123** [comment]
After it crashed like 3 times i said f it and deleted the instance

**Comment by lordalucard123** [comment]
But i will try to get it

**Comment by lordalucard123** [comment]
Even if i removed it i can still get it back but never mind i hope your modpack crashs for alot of other people to numbnuts

**Comment by lordalucard123** [comment]
Even if i removed it i can still get it back but never mind i hope your modpack crashs for alot of other people to numbnuts

**Comment by Y0ungSandwich** [comment]
It doesnt. Thanks for your concern.
