### ISSUE TITLE
Railcraft Textures

### ISSUE THREAD

**Issue by SOCKPUPP3TS** [Y0ungSandwich/Mech-and-Magic#161]
Most of the textures for the railcraft blocks are missing for me (i'm not sure about others, i havent asked). The item icons for them are just completely gone and for some of them when placed they make a solid purpleish color with no textures and others are just invisible.

**Comment by Y0ungSandwich** [comment]
Remove optifine.

**Comment by SOCKPUPP3TS** [comment]
That fixed it, thanks
