### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by jj20021988** [Y0ungSandwich/Mech-and-Magic#162]
everytime I either go to bed or go to exit the game its crashing
turned off vbo's and stopped getting the error message from java that binary se stopped working but still crashes screen stays on leave bed screen or freezes if leaving game
playing Lan games and solo both crash

**Comment by jj20021988** [comment]
How do I do that

Sent from Mail for Windows 10

**Comment by Y0ungSandwich** [comment]
Go to your crash report folder and copy and paste the contents to pastebin.com and link it here.

**Comment by jj20021988** [comment]
There isn’t a folder called crash report only one I can see that might be close is logs is it that one?
Sorry 

Sent from Mail for Windows 10

**Comment by Y0ungSandwich** [comment]
If the game closes it will surely make a crash report.  If not get me the latest logs.

**Comment by jj20021988** [comment]
ive uninstalled the radion driver and installed the one from asus website instead and it seems to have fixed the problem if it happens again il get the logs, it only happens over LAN so I don't know if its my computer struggling to run mine and the other computers game. thank you very much for your help though.
