### ISSUE TITLE
Crash with Garden Gloche

### ISSUE THREAD

**Issue by mza325** [Y0ungSandwich/Mech-and-Magic#164]
When i tried to put redstone and a orchid in a Garden gloche my game crashed when i try to log in its crashes all the time.

Crash log https://pastebin.com/Mcb9pEAQ

**Comment by Y0ungSandwich** [comment]
Guess it didn't like that.  Either roll back the save to a backup if you have one or remove one of the two mods, reboot,  reinstall the pack.  Not much to do here unless you want to to in and mcedit your chunk.  I'll pass the crash on to the authors

**Comment by mza325** [comment]
found out when i look at the garden gloche my game crashes when i ignore the direction of the gloche my game wont crash

**Comment by Y0ungSandwich** [comment]
Do you have optifine installed?

**Comment by mza325** [comment]
i dont should i?

**Comment by Y0ungSandwich** [comment]
Nope just narrowing down ideas as optifine is usually a culprit in this sort of thing g

**Comment by mza325** [comment]
thank you for trying
the admin on the server im playing will be online soon he will remove the gloches.
otherwise i would do it myself with mcedit
