### ISSUE TITLE
chicken duplication

### ISSUE THREAD

**Issue by JulesCezar** [Y0ungSandwich/Mech-and-Magic#165]
Placing chicken from Animal Net sometimes is not removing the chicken from animal net, that allows you to place the chicken 2-3 times (after placing the first one, animal net is not empty, and shows that there is a chicken in it).
For sure this works for Nether Quartz Chickens, but probably for other too.
Unfortunately there is no pattern when it happens.

mod: Hatchery
mod version: 0.3.15
pack version: 1.1.10

**Comment by Y0ungSandwich** [comment]
Can you reproduce in single player?
