### ISSUE TITLE
FMP Microblocks Crash

### ISSUE THREAD

**Issue by DrSyndicate** [Y0ungSandwich/Mech-and-Magic#168]
I was curious if you were aware of the crash related to FMP Microblocks that the mod author has labelled as uncorrectable? Currently, searching the terms 'bookshelf', 'oak' or 'slime' results in an instant and unavoidable crash. I included a crash report so you could see an example. I made it to "bo" before it crashed here.
[crash-2017-06-21_17.02.25-client.txt](https://github.com/Y0ungSandwich/Mech-and-Magic/files/1090730/crash-2017-06-21_17.02.25-client.txt)

**Comment by Y0ungSandwich** [comment]
Havent experienced it. Can you easily reproduce?

**Comment by DrSyndicate** [comment]
Yes. Myself and all of my players have the crash on our private server. The
only way I found around it was to disable FMP Microblocks.

**Comment by Y0ungSandwich** [comment]
I.E. Can you reproduce step by step every single time.

**Comment by DrSyndicate** [comment]
Yes.

Open JEI, search for bookshelf\slime and it crashes.

Thats all we were doing. Like I said on our private server I removed FMP
Microblocks to get around it.

**Comment by Y0ungSandwich** [comment]
Ah just a client side render issue. Nothing on our end. Also its client side not server side. JEI is all client side.
