### ISSUE TITLE
upgraded to new version of mech and magic and players storage blocks are missing

### ISSUE THREAD

**Issue by lostpoet999** [Y0ungSandwich/Mech-and-Magic#169]
Is the data for this mod stored somewhere different? copied world and server properties files from old install to update.  I went from version 1.1.12 to 1.1.13.  After the update everything else seems to be good but all our storage systems are completely missing.

**Comment by Y0ungSandwich** [comment]
Like mentioned in the changelogs this mod had been moved to optional mods.  You must select it before you install the new server files.  Refined storage is the mod in question.  Unless you have a backup of your servers world save the damage is done.

**Comment by lostpoet999** [comment]
Thank you for the super fast reply.  I did backup the server before installing the new version of M&M.  I have a host that ‘one click’ installs the update—is this something they have to make sure is done for the server install? JEI is showing @refined storage items but all our blocks are missing.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Y0ungSandwich** [comment]
You're seeing the blocks because you have it installed on your client.  When you go on the launcher and click create server you'll need to check off refined storage on the right hand side under optional.

**Comment by lostpoet999** [comment]
Okay, I think I got it now.  Thanks so much for speedy response.  I know this is pretty easy for you but I am new at running some of this stuff.  Glad I did a backup first. Haha.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Y0ungSandwich** [comment]
No worries we were all new once.  Just be sure to always check the changelogs.  Feel free to join our discord via the packs main menu.  Changes will always be posted there too.

**Comment by lostpoet999** [comment]
For sure—I actually did read the changelog and honestly should have just done the manual server update.  I let my host do it through web interface.  Great work on the mudpack btw—we are enjoying it quite a bit.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Y0ungSandwich** [comment]
Glad you like it and glad I could help.
