### ISSUE TITLE
Blood Magic - soul network /player files glitched?

### ISSUE THREAD

**Issue by MegaPot** [Y0ungSandwich/Mech-and-Magic#172]
For a certain player, When his bound orb is placed on the blood altar, and viewed using seers sigil or diviner, you only see 4 lp. .. however no lp is transferred to soul network, no matter what is tried. He removed the orb and then no lp is stored. There is no rituals running, no lava crystals, should be no drain on the players soul network. Tried several different orbs with no improvement. Altar has millions of lp available. 

Tried this with same character on single player and it worked fine. 

had the server administrator wipe the 3 player data files, still no lp will store in this players soul network.

Others on the server are able to charge their soul networks on this altar with no issues. 

any suggestion for further troubleshooting?
Thanks

**Comment by Y0ungSandwich** [comment]
I'll ask the obvious question which is sometimes the issue.  The blood orb is paired to the user before going into the altar?

**Comment by MegaPot** [comment]
yes, the orb -is- bound to the player. and displays hs name on the orbs description. 'property of'

**Comment by Y0ungSandwich** [comment]
And no other players are affected? We havent seen this issue ourselves yet. That we are aware of at least.

**Comment by MegaPot** [comment]
That's right, no other players affected. When the blood orb is placed on the altar you can see the number change to 4 or -4.. we think that's reflecting the transfer rate of the LP.. But nothing is transferred. During troubleshooting the server admin stated that there were two sets of player data for each account (3 files each) which he said was unusual. I'm not sure but the second set may be from vampirism? At any rate, still no luck resolving this issue.
