### ISSUE TITLE
Area Crash

### ISSUE THREAD

**Issue by MehToaster** [Y0ungSandwich/Mech-and-Magic#173]
Hi, I have a small server which i run from the same pc i run the client. We are currently 6 players and live in one area. This have worked fine but now when i enter the area the client crash and sends me back to At Launcher. I tried teleporting myself away from the area and it worked but when i enter the area again the client crash. Ive added a crash report of the problem.
Hope for some answers soon.
MehToaster
[crash-2017-08-02_20.02.39-client.txt](https://github.com/Y0ungSandwich/Mech-and-Magic/files/1194855/crash-2017-08-02_20.02.39-client.txt)

**Comment by Y0ungSandwich** [comment]
Uninstall Optifine and try again.

**Comment by MehToaster** [comment]
Thank you, it have worked fine now after uninstalling optifine. But another question; Is it possible to add an admin utility mod? like Ftb utillities or something similar? http://www.9minecraft.net/ftb-utilities-mod/. Whenever i try to install it the server crash due to the error java.lang.NoClassDefFoundError: com/feed_the_beast/ftbl/api/events/FTBLibClientRegistryEvent. I tried downloading a newer
[crash-2017-08-03_03.13.28-server.txt](https://github.com/Y0ungSandwich/Mech-and-Magic/files/1195692/crash-2017-08-03_03.13.28-server.txt)
 version for the FTB Lib but then the same error but a different mod made problems.
[crash-2017-08-03_03.04.11-server.txt](https://github.com/Y0ungSandwich/Mech-and-Magic/files/1195680/crash-2017-08-03_03.04.11-server.txt)
MehToaster

**Comment by Y0ungSandwich** [comment]
Sorry for the delay. At the moment this isn't possible due to the mod conflicts you have encountered. We are looking to add FTBUtils support in MC version 1.12 versioning of the modpack shortly.
