### ISSUE TITLE
Bad resolution?

### ISSUE THREAD

**Issue by Echoeggs** [Y0ungSandwich/Mech-and-Magic#174]
When I load up the game the resolution is wrong, and I don't see anywhere in the options a way to fix it. Also, when I exit fullscreen, I can't even maximize the window

**Comment by Y0ungSandwich** [comment]
Screen shots could help

**Comment by Echoeggs** [comment]
![image](https://user-images.githubusercontent.com/30840046/29084311-39e77b18-7c31-11e7-9663-044bde672e59.png)
![image](https://user-images.githubusercontent.com/30840046/29084331-49b84d06-7c31-11e7-9d20-a23ec4f73348.png)

**Comment by Echoeggs** [comment]
![image](https://user-images.githubusercontent.com/30840046/29084374-68994e64-7c31-11e7-9c07-edfc66906c4f.png)
![image](https://user-images.githubusercontent.com/30840046/29084387-72db627c-7c31-11e7-80e5-ef413c72ef1c.png)

**Comment by Echoeggs** [comment]
![image](https://user-images.githubusercontent.com/30840046/29084401-7d9bb1ee-7c31-11e7-847a-9bb04189a412.png)
![image](https://user-images.githubusercontent.com/30840046/29084412-85001f10-7c31-11e7-9930-99f11c4ef6d1.png)

**Comment by Y0ungSandwich** [comment]
ALT+Enter Doesnt help? Check the ATLauncher resolutions?

**Comment by Echoeggs** [comment]
Ok, I changed the resolution in ATLauncher and set it to start maximized and now it's tolerable, thanks!
