### ISSUE TITLE
Having issues finding correct Version

### ISSUE THREAD

**Issue by GrrGolem** [Y0ungSandwich/Mech-and-Magic#175]
My friend has started a server with Akliz and is using Mech and Magic Version 1.10.2-1.0.0, but there isn't an option for that in the ATLauncher. We need help.

**Comment by Y0ungSandwich** [comment]
Should be using 1.1.14 anyways.

**Comment by Y0ungSandwich** [comment]
Youll always want to use the latest version @GrrGolem
