### ISSUE TITLE
Can't even install!

### ISSUE THREAD

**Issue by OmegaRiley** [Y0ungSandwich/Mech-and-Magic#176]
When I try and download from AT it just crashes... I am inexperience with this kinda thing so I'm not sure if it's me being dumb or if my pc has some kind of problem with the pack. Log is in the text document
[Error Log.txt](https://github.com/Y0ungSandwich/Mech-and-Magic/files/1244053/Error.Log.txt)

**Comment by Y0ungSandwich** [comment]
Issues with any other pack installs?

**Comment by Y0ungSandwich** [comment]
@OmegaRiley This looks like a firewall issue or a broken install of the launcher itself.
