### ISSUE TITLE
Visual Cable Glitches in EnderIO, AE2, ThermalExp

### ISSUE THREAD

**Issue by Physicist1616** [Y0ungSandwich/Mech-and-Magic#178]
I'm loving this pack.

I noticed that sometimes cables glitch out.  It appears to be client-side, but it occurs on (mostly?) the same cable/duct blocks even when other players view on open-to-LAN.

Is this just to-be-expected-and-ignored, or is there some other mod that is making all this happen?

Are there fixes or workarounds?  Can I update a handful of individual mods or forge to make it stop doing this?

3 screenshots at:  http://imgur.com/a/2VeGb

**Comment by Y0ungSandwich** [comment]
We've encountered this on the official server too. As well as certain tile entities being turned around. We're looking into it. But most of our focus is on 1.12.1 development right now. Ill keep this open for updates though.

**Comment by Y0ungSandwich** [comment]
Did a little more testing and we can confirm its all client side. Pipes, wires, and cables are all still functioning properly even when viewed as broke.

**Comment by Physicist1616** [comment]
While client side sounds work-aroundable, sometimes ME Terminals (a pattern terminal for me) also become completely inaccessible.  I had to connect additional cables before my pattern terminal it became visible and interactable.

**Comment by Y0ungSandwich** [comment]
I haven't seen or heard anything about sound.  Nor inaccessible terminals.  Is this a cause of the lines being broken?

**Comment by Y0ungSandwich** [comment]
@Physicist1616 Just to verify this was on single player and on LAN? Not a server using sponge or other modified jars?

**Comment by Physicist1616** [comment]
"While client side [invisible cables] sounds [like something that would be] work-aroundable..." I couldn't get access to an ME pattern terminal because it also went invisible.  
Nothing wrong with sound at all. :)

Single player and on a LAN, no server at all, no modifications from what I got in the ATLauncher.
My optional-mod selections:
https://imgur.com/a/jkvjK

**Comment by Y0ungSandwich** [comment]
Ah I gotcha. I misread my bad. Ill be able to dive more into testing this week. The temporary fix as you said is reconnect a pipe but it will happen again.

**Comment by Y0ungSandwich** [comment]
Should of asked earlier, but what version of the pack did you see this start on?

**Comment by Y0ungSandwich** [comment]
Fixed!
