### ISSUE TITLE
Meneglin and Vampire Forest Biomes in RTG

### ISSUE THREAD

**Issue by Physicist1616** [Y0ungSandwich/Mech-and-Magic#182]
Do the modded biomes happen in RTG?  I haven't seen one, but I see them in non-RTG worldgen.  I know that RTG is *supposed* to have them, but I haven't seen even one.

**Comment by Physicist1616** [comment]
Sidenote, I have seen plenty of Witchwood forests in RTG, just not any of the other modded biomes.

**Comment by Y0ungSandwich** [comment]
RTG has a few issues in their newer versions that add vampirism compatibility. Fixes one thing, but breaks the rest of the pack.
