### ISSUE TITLE
Crashes once loaded

### ISSUE THREAD

**Issue by morfie78** [Y0ungSandwich/Mech-and-Magic#185]
Hi!  I have been playing for a few days.  All of a sudden, my game crashed at my base.  Now, every time I load in, once the chunk starts to load, my game crashes:
[crash-reports.zip](https://github.com/Y0ungSandwich/Mech-and-Magic/files/1349989/crash-reports.zip)

I think there is a bad block or something?  Please let me know what I can do.
Thanks!

**Comment by Y0ungSandwich** [comment]
Reinstall without optifine.

**Comment by morfie78** [comment]
I removed the entire modpack Instance from ATLauncher, confirmed the folder was gone, reinstalled, and relaunched without Optifine.  It still crashed:

[crash-2017-10-02_22.00.52-client.txt](https://github.com/Y0ungSandwich/Mech-and-Magic/files/1350924/crash-2017-10-02_22.00.52-client.txt)

**Comment by Y0ungSandwich** [comment]
Block location: World: (-2418,62,-1199), Chunk: (at 14,3,1 in -152,-75; contains blocks -2432,0,-1200 to -2417,255,-1185), Region: (-5,-3; contains chunks -160,-96 to -129,-65, blocks -2560,0,-1536 to -2049,255,-1025

You can use mcedit to remove that block.  Looks like a blood stained block.  Or if its on a servee you can use the block zap command in the console.  But I've never seen removing optifine not fix this issue.

**Comment by morfie78** [comment]
This is happening on the official Mech and Magic server, so I don't have access to the maps.   I'm not using optifine anymore. I re-installed everything via ATLauncher.   Unfortunately, the crashing is still occurring.

**Comment by Y0ungSandwich** [comment]
Unfortunately it'll have to wait until tomorrow but should be an easy fix.

**Comment by morfie78** [comment]
Thank you, sir!

**Comment by Y0ungSandwich** [comment]
Lemme know if you're able to login today.  Ive zapped the block in question.  If a new crash report generates after this send me that one in case its multiple blocks.

**Comment by morfie78** [comment]
I'm able to log in again.  Thank you!!
