### ISSUE TITLE
Cannot open chests on the lastest update to 1.12.2 in Mech & Magic 

### ISSUE THREAD

**Issue by TunaMods** [Y0ungSandwich/Mech-and-Magic#187]
Downloaded the newest update. started a new world. realized i couldn't open the bonus chest. can open any other kind of chest but vanilla chest wont open at all. Doesn't cause crash, just doesn't open. removed a ton of mods(not all) still doesn't open. Replaced optifine with updated HD C7 optifine. didn't work. changed Forge(about 5 versions, they just caused crashes) So im not really sure what else to do.

**Comment by Y0ungSandwich** [comment]
Tested without any optifine at all?
